#!/bin/sh
p=$(ps -ef | grep ml4w-welcome)
if [[ $p = *'ml4w-welcome.py'* ]]; then
    exit
else
    HERE="$(dirname "$(readlink -f "${0}")")"
    EXEC="${HERE}/usr/bin/ml4w-welcome.py"
    python ${EXEC}
fi